# Generated by Django 3.2 on 2023-09-26 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='about',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, max_length=500, verbose_name='about'),
        ),
    ]
